# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pobres Almas
email: mes.das.almas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Um site dedicado às almas do purgatório

# url: http://localhost:4000
# baseurl: ''
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pobresalmas.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 

github_username: daniel-ufabc

github:
  repo: https://github.com/daniel-ufabc/poor-souls

version: "1.0.0"

# Google Analytics
google_analytics: G-QEX80M0BJK

# author:
#   name: 'Author Name'
#   url: https://twitter.com/yourusername

# # Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Hyde specific settings
# author:
#   name: 'Daniel M. Martin'
#   url: https://twitter.com/yourusername

# paginate: 5
# paginate_path: "page:num"
# paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Plugins (add these if not present)
plugins:
#  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

# Collections
collections:
  book:
    output: true
    permalink: /book/:path/
    sort_by: order
  prayers:
    output: true
    permalink: /prayers/:path/

defaults:
  - scope:
      path: ""
      type: book
    values:
      layout: page
  - scope:
      path: ""
      type: prayers
    values:
      layout: page